### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by kerimkaan** [thompsonemerson/moeda#10]
### Steps to reproduce
moeda 1 usd eur
or 
sudo moeda 1 usd eur
or 
moeda 1 usd

### Expected behavior
Conversion on currencies

### Actual behavior
Error:
Internal server error.

### System configuration
**Node version**: 10.10.0

**npm version**: 6.4.1

**moeda version**: 1.3.3

**Comment by thompsonemerson** [comment]
Hi, @kerimkaan.
We just released a new version solving this and other issues.
can you test for us?! greetings!
