### ISSUE TITLE
Other sources of currency info(not only Fixer.io)

### ISSUE THREAD

**Issue by schvabodka-man** [thompsonemerson/moeda#5]
Hi there! Nice app you've coded but i've encountered one problem with it. Fixer.io simply not support some currencies(in fact currency list of it is barely small, in fact i live in Ukraine and Fixer.io simply don't have support for Ukrainian hryvnia, only rubles). It would be nice if you can implement some other sources of information. Like a google currencies for example. It has simple [API that you could try to parse with some http tools](http://www.google.com/finance/converter?a=$argv1&from=usd&to=uah) and it has mostly every currency in world.

**Comment by thompsonemerson** [comment]
Hi @schvabodka-man, 
Thanks, I'll look the API so we can implement in the next versions. 🚀
